### ISSUE TITLE
Unable to convert the model from keras to CoreML

### ISSUE THREAD

**Issue by Rathna21** [hollance/YOLO-CoreML-MPSNNGraph#51]
2019-04-01 19:13:45.971729: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/Users/ratzzz/PycharmProjects/CoreML/env/lib/python2.7/site-packages/keras/models.py:245: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Traceback (most recent call last):
  File "coreml.py", line 8, in <module>
    image_scale=1/255.)
  File "/Users/ratzzz/PycharmProjects/CoreML/env/lib/python2.7/site-packages/coremltools/converters/keras/_keras_converter.py", line 760, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/Users/ratzzz/PycharmProjects/CoreML/env/lib/python2.7/site-packages/coremltools/converters/keras/_keras_converter.py", line 556, in convertToSpec
    custom_objects=custom_objects)
  File "/Users/ratzzz/PycharmProjects/CoreML/env/lib/python2.7/site-packages/coremltools/converters/keras/_keras2_converter.py", line 209, in _convert
    graph.build()
  File "/Users/ratzzz/PycharmProjects/CoreML/env/lib/python2.7/site-packages/coremltools/converters/keras/_topology2.py", line 750, in build
    self.defuse_activation()
  File "/Users/ratzzz/PycharmProjects/CoreML/env/lib/python2.7/site-packages/coremltools/converters/keras/_topology2.py", line 510, in defuse_activation
    isinstance(k_layer, _keras.layers.SeparableConv1D) or 
AttributeError: 'module' object has no attribute 'SeparableConv1D'

I am using Keras 2.0.6

Could you please help on this issue?

**Comment by elsaneilime** [comment]
Can you post a description of how you resolved this issue?
